### ISSUE TITLE
Exporting story to GitHub for new stories returns 404 error

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/alliance-community#100]
Analysis shows that there is a missing data field in backlog table: github_repo, that needs to contain the name of the repository to which this story should be exported.

Add New Story logic should insert this field value.

**Comment by srb-github** [comment]
form.py >> BacklogNewForm >> save

teamNameFromRequest = request.session.get('teamName')
        logger.debug(teamNameFromRequest)

        if 'Alliance Test Team' == teamNameFromRequest :
            backlog.github_repo = "alliance-community"
        elif 'All Megastars' == teamNameFromRequest :
            backlog.github_repo = "alliance-community"
        elif 'North Stars' == teamNameFromRequest :
            backlog.github_repo = "nexus-community"
        else:
            backlog.github_repo = "test-community"
