### ISSUE TITLE
import process is not verifying the source of received packages

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/alliance-community#13]
_From @goiaba on July 23, 2015 20:55_

There is a method called verify_source in the GitHubWebhookView class (github_webhook_view.py module) that must be reviewed because it is not working properly. There should be a call to this method when a POST is received (that is commented out now), to validate the origin of the package as a github server.

_Copied from original issue: NorthBridge/playbook#31_

**Comment by hectron** [comment]
I believe that this issue is in reference to verifying the source. Check that the headers indicate that this comes from Github.
