### ISSUE TITLE
Logging functionality is not working

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/alliance-community#14]
_From @goiaba on July 23, 2015 20:49_

Logging framework is configured to write to a file (playbook.log) and rotate every week, but it is not writing anywhere.

_Copied from original issue: NorthBridge/playbook#30_

**Comment by kdflint** [comment]
Further comments from @martsberger 

Hi team,

I did a fresh clone of the repo and was following the Mac installation instructions and when I tried to migrate the database

> ./manage.py migrate

I get an error:

ConfigParser.NoSectionError: No section: 'formatters'

The traceback only references our code in the settings file:
File "/Users/brad/projects/alliance/alliance-community/alliance/config/settings/base.py", line 63, in <module>
    logging.config.fileConfig(os.path.join(CORE_PROJECT_DIR, 'logging.ini'))

I commented out that line to get back on my feet and keep working. I've not used a logging.config with an ini file before (I've always just defined the logging with a python dictionary). If anyone knows anything about this and can help out, that would be great.

P.S.
Not directly related, but this line
CORE_PROJECT_DIR = os.path.join(BASE_DIR, 'alliance/core')
Looks like it would cause problems on Windows because it uses the forward slash path separator. It should probably be:
CORE_PROJECT_DIR = os.path.join(BASE_DIR, 'alliance', 'core')

**Comment by hectron** [comment]
@rebeldroid12 can you please take a look at this issue? @martsberger can be a point of contact.

**Comment by rebeldroid12** [comment]
Merged the changes in #58 commit: https://github.com/rebeldroid12/alliance-community/commit/cdba13d3de06f97c5ae5c9752a1a62deebf715d4

**Comment by hectron** [comment]
![](http://i.giphy.com/v3zrOsLhw30D6.gif)
Awesome job, @rebeldroid12 !
