### ISSUE TITLE
settings_builder.py has a syntax error

### ISSUE THREAD

**Issue by martsberger** [NorthBridge/alliance-community#16]
`if __name__ == __main__:`

should be

`if __name__ == '__main__':`

'__main__' is a string in quotes.

I'm just going to fix this and check it in, but I want to have a gentle reminder of two things that should be common practice to help catch little things like this that can slip into a code base.
1. Your linter should warn you of this (PyCharm marked the file as red and put a red underline under the offending code).
2. You should run code before checking it in. Running the settings_builder.py file resulted in a NameError, just running the code would catch this.

**Comment by kdflint** [comment]
I am going to close this but we will discuss at our upcoming meeting. One of our goals there is to discuss code review procedures.
