### ISSUE TITLE
Set up testing framework

### ISSUE THREAD

**Issue by hectron** [NorthBridge/alliance-community#21]
It comes of no surprise that a solid testing framework is necessary for a successful open source project. The following website is an excellent resource explaining how to get started with testing a Django application: http://dezoito.github.io/2015/09/21/how-to-test-django-applications_pt1/

**Comment by rebeldroid12** [comment]
@hectron can take on testing

**Comment by hectron** [comment]
I tried this out and it looks valid! Currently on master (on commit e8aad1b8c50f1cd47c9d44945185cc4b47580fa7), it is **not** functional. This is because the settings of the project are a bit messed up. However, I was able to get it working by modifying `manage.py`, `config/settings/base.py` and `config/settings/dev.py`. This is a part of a branch that @rebeldroid12 and I are using to get the project to a workable state to test the acceptance of many issues.

Therefore, I'm ok with closing this out and accepting it.

**Comment by kdflint** [comment]
I'm a little worried that we are doing redundant work... the heroku branch solved a lot of settings problems and is now fully functional at https://alliance-dev.herokuapp.com/alliance/apps/backlog/

Is it possible for use to get Pull #40 approved so we can get to a stable core?

**Comment by hectron** [comment]
Perhaps we can merge it in. There are a few comments that I left in there. It seems that a lot of the original structure was altered and/or not being used. I think there's a way that we can simplify it so that it's not so complex.

Some examples include reducing the number of `settings` files.
