### ISSUE TITLE
nullable database fields require input in the Admin interface

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/alliance-community#25]
Ping @kdflint for a comprehensive list, but for example:

Backlog table/model: sprint, module, skills, notes, github number, update dttm.

These should all be optional inputs. (Works ok when I use sql to insert backlog data with null on these columns.) 

I will supply a complete list for whoever takes this up. 

-Kathy

**Comment by kdflint** [comment]
To see the problem, navigate to https://alliance-dev.herokuapp.com/admin

Log in as `kdflint` \ `password0`

Go to the Backlogs model

Click "Add Backlog"

Enter nothing, and click "Save"

A bunch of red errors will show up saying "This field is required"

The only fields that should be required in order to save a record are Title, Status and Create Date.

Can we make all the other fields optional with respect to the django model?

This is how the database is specified:

![screenshot from 2015-10-08 11 08 31](https://cloud.githubusercontent.com/assets/1907202/10372352/07314fda-6dad-11e5-82a4-6076d71fa430.png)

**Comment by rebeldroid12** [comment]
https://github.com/NorthBridge/alliance-community/pull/34

**Comment by kdflint** [comment]
This is working in alliance-dev
