### ISSUE TITLE
The project should have a consistent style

### ISSUE THREAD

**Issue by martsberger** [NorthBridge/alliance-community#37]
The codebase does not currently have a consistent style. The major things that I notice that are inconsistent when reading the code are:

1. Naming convention, when to use CapWords vs lower_with_underscores.
2. Line lengths. It looks like some statements have been made multiline to fit an 80 character line length while other lines go well over 80 characters.
3. Indenting multiline statements. We don't have a consistent rule for indenting the 2nd (3rd, etc.) line of a multi line statement.

My preference is to follow what is called pep8 style. This is the style guide laid out in the Python language official Python Enhancement Proposal (PEP) 0008 (https://www.python.org/dev/peps/pep-0008/).  (It's not a short document, but you can jump to the relevant sections on the three points I listed above.)

Three reasons to use pep8 style:
1. The style will be recognizable and the code will be easy to read by any new volunteer with Python experience.
2. Volunteers for early in their career will get used to the way Python code looks in other professional Python shops.
3. If you're using a Python linter (recommended), this is the style it will tell you to adhere to. If your editor/IDE has a Python plugin, it will "do the right thing" for you and you won't have to think about it.

**Comment by rebeldroid12** [comment]
@martsberger  I can take this on.
