### ISSUE TITLE
 Logout from Alliance should give graceful output

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/alliance-community#71]

**Comment by goiaba** [comment]
@kdflint The version deployed in heroku gives me a 404 error when my session is expired and the backlog page tries to verify if the data displayed are outdated.

Is this issue related to what I explained above? If so, I will create a pull request with the solution (it is simple, just a "/" in the wrong place).

**Comment by kdflint** [comment]
@goiba : @rebeldroid12 coded a fix for this but I only tested the explicit logout scenario. Did not test the timeout scenario.

Please go ahead and create another pull if you can fix the timeout scenario.
